version: "3.8"

services:
  strictproto-dev:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: strictproto-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    tty: true
